// AUTO-GENERATED by build_gallery.js — Bookcubers media library
export type GalleryType = "image" | "video";

export interface GalleryItem {
  src: string;
  type: GalleryType;
  caption: string;
  category: string;
  year: number | null;
}

export interface GalleryCategory {
  id: string;
  title_en: string;
  title_es: string;
  desc_en: string;
  desc_es: string;
}

export const galleryCategories: GalleryCategory[] = [
  {
    "id": "education",
    "title_en": "Education & Critical Reading",
    "title_es": "Educación & Lectura Crítica",
    "desc_en": "Field schools, media literacy, and creative civic learning across Bolivian communities.",
    "desc_es": "Escuelas itinerantes, alfabetización mediática y aprendizaje cívico creativo en comunidades de Bolivia."
  },
  {
    "id": "sovereignty",
    "title_en": "Indigenous Digital Sovereignty — Gengo Academy",
    "title_es": "Soberanía Digital Indígena — Gengo Academy",
    "desc_en": "Bringing technology and digital rights to indigenous communities in their own languages.",
    "desc_es": "Llevando tecnología y derechos digitales a comunidades indígenas en sus propias lenguas."
  },
  {
    "id": "territory",
    "title_en": "Territory & Environment — The Zamuco Protocol",
    "title_es": "Territorio & Medio Ambiente — The Zamuco Protocol",
    "desc_en": "Accompanying Ayoreode communities to protect their territory and ensure community ownership.",
    "desc_es": "Acompañando a las comunidades ayoreode en la defensa de su territorio y el community ownership."
  },
  {
    "id": "community",
    "title_en": "Community & Volunteers",
    "title_es": "Comunidad & Voluntariado",
    "desc_en": "Building a youth volunteer network across indigenous communities of the Chaco.",
    "desc_es": "Construyendo una red juvenil de voluntariado en las comunidades indígenas del Chaco."
  },
  {
    "id": "global",
    "title_en": "Global Recognition",
    "title_es": "Reconocimiento Internacional",
    "desc_en": "Bookcubers founders representing Bolivia at the UN, UNESCO, UNODC and global youth forums.",
    "desc_es": "Fundadores de Bookcubers representando a Bolivia ante la ONU, UNESCO, UNODC y foros juveniles globales."
  },
  {
    "id": "ai-governance",
    "title_en": "AI Governance — CJIAL",
    "title_es": "Gobernanza de IA — CJIAL",
    "desc_en": "Launching Latin America's youth AI-governance council and its first Youth Declaration on AI.",
    "desc_es": "Lanzamiento del consejo juvenil latinoamericano de gobernanza de IA y su primera Declaración Juvenil sobre IA."
  },
  {
    "id": "accessibility",
    "title_en": "Accessibility & Inclusion — JOPÓI",
    "title_es": "Accesibilidad & Inclusión — JOPÓI",
    "desc_en": "Making democracy accessible: legislators experience disability barriers firsthand.",
    "desc_es": "Democracia accesible: los legisladores viven de primera mano las barreras de la discapacidad."
  }
];

export const galleryItems: GalleryItem[] = [
  {
    "src": "/gallery/un-plenary-session-speech-ldc3-carlos-andres-olivera-caballero-bookcub.mp4",
    "type": "video",
    "caption": "UN Plenary Session Speech (LDC3) - Carlos Andres Olivera Caballero",
    "category": "global",
    "year": null
  },
  {
    "src": "/gallery/video-de-gengo-academy-en-accion-bookcubers-2.mp4",
    "type": "video",
    "caption": "Video de Gengo Academy en acción 2",
    "category": "sovereignty",
    "year": null
  },
  {
    "src": "/gallery/video-de-gengo-academy-en-accion-bookcubers-3.mp4",
    "type": "video",
    "caption": "Video de Gengo Academy en acción 3",
    "category": "sovereignty",
    "year": null
  },
  {
    "src": "/gallery/video-de-gengo-academy-en-accion-bookcubers.mp4",
    "type": "video",
    "caption": "Video de Gengo Academy en acción",
    "category": "sovereignty",
    "year": null
  },
  {
    "src": "/gallery/actividad-escuela-itinerante-aguarague-bookcubers-2.jpg",
    "type": "image",
    "caption": "Escuela Itinerante Aguaragüe",
    "category": "education",
    "year": null
  },
  {
    "src": "/gallery/actividad-escuela-itinerante-aguarague-bookcubers-3.jpg",
    "type": "image",
    "caption": "Escuela Itinerante Aguaragüe",
    "category": "education",
    "year": null
  },
  {
    "src": "/gallery/actividad-escuela-itinerante-aguarague-bookcubers-4.jpg",
    "type": "image",
    "caption": "Escuela Itinerante Aguaragüe",
    "category": "education",
    "year": null
  },
  {
    "src": "/gallery/actividad-escuela-itinerante-aguarague-bookcubers.jpg",
    "type": "image",
    "caption": "Escuela Itinerante Aguaragüe",
    "category": "education",
    "year": null
  },
  {
    "src": "/gallery/actividad-de-capacitacion-en-media-literacy-y-el-metodo-lede-bookcuber.jpg",
    "type": "image",
    "caption": "Capacitación en Media Literacy y el Metodo LEDE",
    "category": "education",
    "year": null
  },
  {
    "src": "/gallery/actividad-de-capacitacion-en-media-literacy-y-el-metodo-lede-bookcuber-2.jpg",
    "type": "image",
    "caption": "Capacitación en Media Literacy y el Metodo LEDE",
    "category": "education",
    "year": null
  },
  {
    "src": "/gallery/actividad-de-capacitacion-en-media-literacy-y-el-metodo-lede-bookcuber-3.jpg",
    "type": "image",
    "caption": "Capacitación en Media Literacy y el Metodo LEDE",
    "category": "education",
    "year": null
  },
  {
    "src": "/gallery/actividad-de-doble-helice-creativa-bookcubers-en-la-comunidad-degui-y-.jpg",
    "type": "image",
    "caption": "Doble hélice creativa Bookcubers en la Comunidad Degüí y Garay",
    "category": "education",
    "year": null
  },
  {
    "src": "/gallery/actividad-de-doble-helice-creativa-bookcubers-en-la-comunidad-degui-y--2.jpg",
    "type": "image",
    "caption": "Doble hélice creativa Bookcubers en la Comunidad Degüí y Garay",
    "category": "education",
    "year": null
  },
  {
    "src": "/gallery/actividad-de-doble-helice-creativa-bookcubers-en-la-comunidad-degui-y--3.jpg",
    "type": "image",
    "caption": "Doble hélice creativa Bookcubers en la Comunidad Degüí y Garay",
    "category": "education",
    "year": null
  },
  {
    "src": "/gallery/actividad-de-soberania-digital-indigena-bookcubers-en-la-comunidad-san.jpg",
    "type": "image",
    "caption": "Soberanía DIgital Indigena Bookcubers en la Comunidad San Antonio de Lomerío, Zapocó",
    "category": "sovereignty",
    "year": null
  },
  {
    "src": "/gallery/actividad-de-soberania-digital-indigena-bookcubers-en-la-comunidad-san-2.jpg",
    "type": "image",
    "caption": "Soberanía DIgital Indigena Bookcubers en la Comunidad San Antonio de Lomerío, Zapocó",
    "category": "sovereignty",
    "year": null
  },
  {
    "src": "/gallery/actividad-de-creatividad-estructural-bookcubers-bookcubers-2.jpg",
    "type": "image",
    "caption": "Creatividad estructural Bookcubers",
    "category": "education",
    "year": null
  },
  {
    "src": "/gallery/actividad-de-creatividad-estructural-bookcubers-bookcubers-3.jpg",
    "type": "image",
    "caption": "Creatividad estructural Bookcubers",
    "category": "education",
    "year": null
  },
  {
    "src": "/gallery/actividad-de-creatividad-estructural-bookcubers-bookcubers-4.jpg",
    "type": "image",
    "caption": "Creatividad estructural Bookcubers",
    "category": "education",
    "year": null
  },
  {
    "src": "/gallery/actividad-de-creatividad-estructural-bookcubers-bookcubers.jpg",
    "type": "image",
    "caption": "Creatividad estructural Bookcubers",
    "category": "education",
    "year": null
  },
  {
    "src": "/gallery/actividad-huertos-aula-bookcubers-2.jpg",
    "type": "image",
    "caption": "Huertos-aula",
    "category": "territory",
    "year": null
  },
  {
    "src": "/gallery/actividad-huertos-aula-bookcubers-3.jpg",
    "type": "image",
    "caption": "Huertos-aula",
    "category": "territory",
    "year": null
  },
  {
    "src": "/gallery/actividad-huertos-aula-bookcubers.jpg",
    "type": "image",
    "caption": "Huertos-aula",
    "category": "territory",
    "year": null
  },
  {
    "src": "/gallery/bookcubers-entrena-a-la-plataforma-de-jovenes-drafters-bookcubers-2.jpg",
    "type": "image",
    "caption": "Bookcubers entrena a la Plataforma de Jóvenes Drafters",
    "category": "education",
    "year": null
  },
  {
    "src": "/gallery/bookcubers-entrena-a-la-plataforma-de-jovenes-drafters-bookcubers-3.jpg",
    "type": "image",
    "caption": "Bookcubers entrena a la Plataforma de Jóvenes Drafters",
    "category": "education",
    "year": null
  },
  {
    "src": "/gallery/bookcubers-entrena-a-la-plataforma-de-jovenes-drafters-bookcubers-4.jpg",
    "type": "image",
    "caption": "Bookcubers entrena a la Plataforma de Jóvenes Drafters",
    "category": "education",
    "year": null
  },
  {
    "src": "/gallery/bookcubers-entrena-a-la-plataforma-de-jovenes-drafters-bookcubers.jpg",
    "type": "image",
    "caption": "Bookcubers entrena a la Plataforma de Jóvenes Drafters",
    "category": "education",
    "year": null
  },
  {
    "src": "/gallery/carlos-fundador-de-bookcubers-en-la-youth-democracy-network-promoviend.jpg",
    "type": "image",
    "caption": "Carlos Fundador de Bookcubers en la Youth Democracy Network promoviendo la Soberanía digital indígena de Bookcubers en Panamá",
    "category": "global",
    "year": null
  },
  {
    "src": "/gallery/carlos-fundador-de-bookcubers-en-la-youth-democracy-network-promoviend-2.jpg",
    "type": "image",
    "caption": "Carlos Fundador de Bookcubers en la Youth Democracy Network promoviendo la Soberanía digital indígena de Bookcubers en Panamá",
    "category": "global",
    "year": null
  },
  {
    "src": "/gallery/carlos-fundador-de-bookcubers-en-la-youth-democracy-network-promoviend-3.jpg",
    "type": "image",
    "caption": "Carlos Fundador de Bookcubers en la Youth Democracy Network promoviendo la Soberanía digital indígena de Bookcubers en Panamá",
    "category": "global",
    "year": null
  },
  {
    "src": "/gallery/carlos-fundador-de-bookcubers-en-la-youth-democracy-network-promoviend-4.jpg",
    "type": "image",
    "caption": "Carlos Fundador de Bookcubers en la Youth Democracy Network promoviendo la Soberanía digital indígena de Bookcubers en Panamá",
    "category": "global",
    "year": null
  },
  {
    "src": "/gallery/carlos-olivera-fundador-de-bookcubers-en-el-4-global-youth-forum-de-la.jpg",
    "type": "image",
    "caption": "Carlos Olivera fundador de Bookcubers en el 4º Global Youth Forum de la UNODC en Tokio",
    "category": "global",
    "year": null
  },
  {
    "src": "/gallery/carlos-olivera-fundador-de-bookcubers-en-el-4-global-youth-forum-de-la-2.jpg",
    "type": "image",
    "caption": "Carlos Olivera fundador de Bookcubers en el 4º Global Youth Forum de la UNODC en Tokio, hablando sobre el modelo LEDE y la escuela Aguaragüe",
    "category": "global",
    "year": null
  },
  {
    "src": "/gallery/carlos-olivera-fundador-de-bookcubers-como-co-chair-en-el-4-global-you.jpg",
    "type": "image",
    "caption": "Carlos Olivera fundador de Bookcubers, como co-chair en el 4º Global Youth Forum de la UNODC en Tokio",
    "category": "global",
    "year": null
  },
  {
    "src": "/gallery/carlos-olivera-siendo-premiado-campeon-mundial-unesco-en-produccion-au.jpg",
    "type": "image",
    "caption": "Carlos Olivera siendo premiado campeón mundial UNESCO en producción audiovisual, durante el Foro Internacional de la Juventud en China 2025",
    "category": "global",
    "year": 2025
  },
  {
    "src": "/gallery/carlos-olivera-siendo-premiado-campeon-mundial-unesco-en-produccion-au-2.jpg",
    "type": "image",
    "caption": "Carlos Olivera siendo premiado campeón mundial UNESCO en producción audiovisual, durante el Foro Internacional de la Juventud en China 2025",
    "category": "global",
    "year": 2025
  },
  {
    "src": "/gallery/carlos-olivera-siendo-premiado-campeon-mundial-unesco-en-produccion-au-3.jpg",
    "type": "image",
    "caption": "Carlos Olivera siendo premiado campeón mundial UNESCO en producción audiovisual, durante el Foro Internacional de la Juventud en China 2025",
    "category": "global",
    "year": 2025
  },
  {
    "src": "/gallery/carlos-fundador-de-bookcubers-delegado-de-bolivia-en-ldc3-de-naciones-.jpg",
    "type": "image",
    "caption": "Carlos fundador de Bookcubers Delegado de Bolivia en LDC3 de Naciones Unidas en Turkmenistan",
    "category": "global",
    "year": null
  },
  {
    "src": "/gallery/carlos-y-fernando-miembros-de-bookcubers-recibiendo-el-premio-joven-ga.jpg",
    "type": "image",
    "caption": "Carlos y Fernando, miembros de Bookcubers recibiendo el Premio Joven, galardón más importante de la Gobernación de Santa Cruz, Bolivia, por su trabajo en medio ambiente y desarrolo juvenil ©Bookcub",
    "category": "global",
    "year": null
  },
  {
    "src": "/gallery/fernando-aireyu-chajtur-recibiendo-un-reconocimiento-de-la-uagrm-por-s.jpg",
    "type": "image",
    "caption": "Fernando Aireyú Chajtur recibiendo un reconocimiento de la UAGRM por su colaboración en The Zamuco Protocol",
    "category": "territory",
    "year": null
  },
  {
    "src": "/gallery/fernando-chajtur-inaugurando-salas-refaccionadas-en-conjunto-con-la-ua.jpg",
    "type": "image",
    "caption": "Fernando Chajtur inaugurando salas refaccionadas en conjunto con la UAGRM para llevar a cabo el proyecto The Zamuco Protocol",
    "category": "territory",
    "year": null
  },
  {
    "src": "/gallery/fernando-y-voluntarios-de-bookcubers-consultando-con-con-las-comunidad.jpg",
    "type": "image",
    "caption": "Fernando y voluntarios de Bookcubers consultando con con las comunidades ayoreas sobre el TEJIDO PERPETUO para asegurar community ownership",
    "category": "territory",
    "year": null
  },
  {
    "src": "/gallery/fernando-y-voluntarios-de-bookcubers-consultando-con-con-las-comunidad-2.jpg",
    "type": "image",
    "caption": "Fernando y voluntarios de Bookcubers consultando con con las comunidades ayoreas sobre el TEJIDO PERPETUO para asegurar community ownership",
    "category": "territory",
    "year": null
  },
  {
    "src": "/gallery/fernando-y-voluntarios-de-bookcubers-consultando-con-con-las-comunidad-3.jpg",
    "type": "image",
    "caption": "Fernando y voluntarios de Bookcubers consultando con con las comunidades ayoreas sobre el TEJIDO PERPETUO para asegurar community ownership",
    "category": "territory",
    "year": null
  },
  {
    "src": "/gallery/fernando-y-voluntarios-de-bookcubers-recorriendo-el-corredor-ayoreode-.jpg",
    "type": "image",
    "caption": "Fernando y voluntarios de Bookcubers recorriendo el CORREDOR AYOREODE del Zamuco Protocal para asegurar desarrolo sostenbile",
    "category": "territory",
    "year": null
  },
  {
    "src": "/gallery/fernando-y-voluntarios-de-bookcubers-recorriendo-el-corredor-ayoreode--2.jpg",
    "type": "image",
    "caption": "Fernando y voluntarios de Bookcubers recorriendo el CORREDOR AYOREODE del Zamuco Protocal para asegurar desarrolo sostenbile",
    "category": "territory",
    "year": null
  },
  {
    "src": "/gallery/miembros-de-bookcubers-captando-nuevos-voluntarios-en-las-comunidades-.jpg",
    "type": "image",
    "caption": "Miembros de Bookcubers captando nuevos voluntarios en las comunidades indígenas de Camiri, Charagua Iyambae",
    "category": "community",
    "year": null
  },
  {
    "src": "/gallery/miembros-de-bookcubers-captando-nuevos-voluntarios-en-las-comunidades--2.jpg",
    "type": "image",
    "caption": "Miembros de Bookcubers captando nuevos voluntarios en las comunidades indígenas de Camiri, Charagua Iyambae",
    "category": "community",
    "year": null
  },
  {
    "src": "/gallery/miembros-de-bookcubers-captando-nuevos-voluntarios-en-las-comunidades--3.jpg",
    "type": "image",
    "caption": "Miembros de Bookcubers captando nuevos voluntarios en las comunidades indígenas de Camiri, Charagua Iyambae",
    "category": "community",
    "year": null
  },
  {
    "src": "/gallery/municipal-government-post-on-gengo-academy-bookcubers.jpg",
    "type": "image",
    "caption": "Municipal Government post on Gengo Academy",
    "category": "sovereignty",
    "year": null
  },
  {
    "src": "/gallery/u-s-embassy-post-on-gengo-academy.jpg",
    "type": "image",
    "caption": "U.S. Embassy Post on Gengo Academy",
    "category": "sovereignty",
    "year": null
  },
  {
    "src": "/gallery/post-en-redes-sobre-nuestros-huertos-aula-bookcubers-2.jpg",
    "type": "image",
    "caption": "Post en redes sobre nuestros huertos-aula",
    "category": "territory",
    "year": null
  },
  {
    "src": "/gallery/post-en-redes-sobre-nuestros-huertos-aula-bookcubers.jpg",
    "type": "image",
    "caption": "Post en redes sobre nuestros huertos-aula",
    "category": "territory",
    "year": null
  },
  {
    "src": "/gallery/cristhian-vargas-cosp19-speech-united-nations.mp4",
    "type": "video",
    "caption": "Cristhian Vargas, co-founder de Bookcubers, presentando en COSP19 (19ª Conferencia de Estados Partes de la CRPD) en Naciones Unidas — abogando por derechos de personas con discapacidad e indígenas",
    "category": "global",
    "year": 2026
  },
  {
    "src": "/gallery/cristhian-vargas-cosp19-united-nations-session.jpg",
    "type": "image",
    "caption": "Cristhian Vargas, co-founder de Bookcubers, en la sesión de COSP19 en la sede de Naciones Unidas, Nueva York",
    "category": "global",
    "year": 2026
  },
  {
    "src": "/gallery/cristhian-vargas-cosp19-un-emblem-new-york.jpg",
    "type": "image",
    "caption": "Cristhian Vargas, co-founder de Bookcubers, en la sede de Naciones Unidas durante COSP19, Nueva York",
    "category": "global",
    "year": 2026
  },
  {
    "src": "/gallery/bookcubers-delegation-cosp19-united-nations-new-york.jpg",
    "type": "image",
    "caption": "Cristhian Vargas (co-founder de Bookcubers) junto a la delegación de pueblos indígenas y personas con discapacidad en COSP19, sede de Naciones Unidas, Nueva York",
    "category": "global",
    "year": 2026
  },
  {
    "src": "/gallery/cristhian-vargas-cosp19-general-assembly-hall.jpg",
    "type": "image",
    "caption": "Cristhian Vargas, co-founder de Bookcubers, en el Salón de la Asamblea General de las Naciones Unidas durante COSP19, Nueva York",
    "category": "global",
    "year": 2026
  },
  {
    "src": "/gallery/cristhian-vargas-cosp19-general-assembly-new-york.jpg",
    "type": "image",
    "caption": "Cristhian Vargas, co-founder de Bookcubers, en la Asamblea General de las Naciones Unidas durante COSP19, Nueva York",
    "category": "global",
    "year": 2026
  },
  {
    "src": "/gallery/co-jopoi-01.jpg",
    "type": "image",
    "caption": "Proyecto JOPÓI: Primera Sesión Espejo en el hemiciclo de la Asamblea Legislativa Departamental de Santa Cruz",
    "category": "accessibility",
    "year": 2026
  },
  {
    "src": "/gallery/co-jopoi-02.jpg",
    "type": "image",
    "caption": "Proyecto JOPÓI: asambleístas departamentales vendados experimentan de primera mano las barreras de accesibilidad",
    "category": "accessibility",
    "year": 2026
  },
  {
    "src": "/gallery/co-cjial-03.jpg",
    "type": "image",
    "caption": "Lanzamiento del CJIAL: Consejo Juvenil de Inteligencia Artificial Latinoamericano, junto a autoridades de la UAGRM",
    "category": "ai-governance",
    "year": 2026
  },
  {
    "src": "/gallery/co-jopoi-04.jpg",
    "type": "image",
    "caption": "Proyecto JOPÓI: simulacro de sesión legislativa por la inclusión de personas con discapacidad visual",
    "category": "accessibility",
    "year": 2026
  },
  {
    "src": "/gallery/co-cjial-05.jpg",
    "type": "image",
    "caption": "Lanzamiento del CJIAL en la UAGRM: presentación de la primera Declaración Juvenil sobre Inteligencia Artificial",
    "category": "ai-governance",
    "year": 2026
  },
  {
    "src": "/gallery/co-japan-06.jpg",
    "type": "image",
    "caption": "Carlos Olivera junto a jóvenes líderes del Youth Leader Fund for a World without Nuclear Weapons (ONU-UNITAR), Japón 2026",
    "category": "global",
    "year": 2026
  },
  {
    "src": "/gallery/co-japan-07.jpg",
    "type": "image",
    "caption": "Carlos Olivera en las sesiones de trabajo del Youth Leader Fund de la ONU (UNITAR), Japón",
    "category": "global",
    "year": 2026
  },
  {
    "src": "/gallery/co-japan-08.jpg",
    "type": "image",
    "caption": "Carlos Olivera durante la Visita de Estudio a Japón del Youth Leader Fund de la ONU (UNITAR)",
    "category": "global",
    "year": 2026
  },
  {
    "src": "/gallery/co-japan-09.jpg",
    "type": "image",
    "caption": "Carlos Olivera con la cohorte internacional del Youth Leader Fund de la ONU (UNITAR), Japón 2026",
    "category": "global",
    "year": 2026
  },
  {
    "src": "/gallery/co-japan-10.jpg",
    "type": "image",
    "caption": "Presentación del Manual de Desarme del Youth Leader Fund de la ONU: Carlos Olivera, coautor del capítulo sobre IA y tecnología cívica offline",
    "category": "global",
    "year": 2026
  },
  {
    "src": "/gallery/co-japan-12.jpg",
    "type": "image",
    "caption": "Carlos Olivera con la cohorte global del Youth Leader Fund de la ONU (UNITAR) en Japón",
    "category": "global",
    "year": 2026
  },
  {
    "src": "/gallery/co-toyp-13.jpg",
    "type": "image",
    "caption": "Premios TOYP Santa Cruz 2026 (JCI Oriente): Diez Jóvenes Sobresalientes",
    "category": "global",
    "year": 2026
  },
  {
    "src": "/gallery/co-japan-14.jpg",
    "type": "image",
    "caption": "Visita de Estudio a Japón del Youth Leader Fund de la ONU (UNITAR): Hiroshima y Nagasaki",
    "category": "global",
    "year": 2026
  },
  {
    "src": "/gallery/co-cjial-15.jpg",
    "type": "image",
    "caption": "CJIAL: entrega de la primera Declaración Juvenil sobre Inteligencia Artificial en la UAGRM",
    "category": "ai-governance",
    "year": 2026
  },
  {
    "src": "/gallery/co-japan-16.jpg",
    "type": "image",
    "caption": "Certificado de culminación del Youth Leader Fund for a World without Nuclear Weapons (ONU-UNITAR), Japón 2026: Carlos Andrés Olivera Caballero",
    "category": "global",
    "year": 2026
  },
  {
    "src": "/gallery/co-japan-17.jpg",
    "type": "image",
    "caption": "Carlos Olivera con líderes y organizadores del Youth Leader Fund de la ONU (UNITAR), Japón",
    "category": "global",
    "year": 2026
  },
  {
    "src": "/gallery/co-cjial-18.jpg",
    "type": "image",
    "caption": "Lanzamiento oficial del CJIAL: Consejo Juvenil de IA Latinoamericano en la UAGRM, Santa Cruz",
    "category": "ai-governance",
    "year": 2026
  },
  {
    "src": "/gallery/co-cjial-19.jpg",
    "type": "image",
    "caption": "Lanzamiento del CJIAL en el Módulo 284 de Relaciones Internacionales de la UAGRM",
    "category": "ai-governance",
    "year": 2026
  },
  {
    "src": "/gallery/co-toyp-20.jpg",
    "type": "image",
    "caption": "Carlos Olivera celebra su reconocimiento en los Premios TOYP Santa Cruz 2026",
    "category": "global",
    "year": 2026
  },
  {
    "src": "/gallery/co-japan-21.jpg",
    "type": "image",
    "caption": "Carlos Olivera representa a Bolivia en el Youth Leader Fund de la ONU (UNITAR), Japón 2026",
    "category": "global",
    "year": 2026
  },
  {
    "src": "/gallery/co-toyp-22.jpg",
    "type": "image",
    "caption": "Carlos Olivera, galardonado en los Premios TOYP Santa Cruz 2026 (JCI Oriente)",
    "category": "global",
    "year": 2026
  },
  {
    "src": "/gallery/co-japan-23.jpg",
    "type": "image",
    "caption": "Carlos Olivera con la cohorte del Youth Leader Fund de la ONU (UNITAR) en Japón",
    "category": "global",
    "year": 2026
  },
  {
    "src": "/gallery/co-cjial-24.jpg",
    "type": "image",
    "caption": "Equipo del CJIAL en el lanzamiento oficial en la UAGRM: gobernanza de IA con enfoque en derechos humanos",
    "category": "ai-governance",
    "year": 2026
  },
  {
    "src": "/gallery/co-toyp-25.jpg",
    "type": "image",
    "caption": "Carlos Olivera recibe el Premio TOYP Santa Cruz 2026: categoría Contribución a los Derechos Humanos y la Paz Mundial",
    "category": "global",
    "year": 2026
  },
  {
    "src": "/gallery/co-toyp-26.jpg",
    "type": "image",
    "caption": "Premios TOYP Santa Cruz 2026 (JCI Oriente): categoría Derechos Humanos y Paz Mundial",
    "category": "global",
    "year": 2026
  },
  {
    "src": "/gallery/co-japan-27.jpg",
    "type": "image",
    "caption": "Carlos Olivera y jóvenes líderes del mundo en el Youth Leader Fund de la ONU (UNITAR), Japón",
    "category": "global",
    "year": 2026
  },
  {
    "src": "/gallery/co-cjial-28.jpg",
    "type": "image",
    "caption": "CJIAL: Consejo Juvenil de Inteligencia Artificial Latinoamericano, lanzamiento en la UAGRM",
    "category": "ai-governance",
    "year": 2026
  },
  {
    "src": "/gallery/co-japan-29.jpg",
    "type": "image",
    "caption": "Cohorte del Youth Leader Fund for a World without Nuclear Weapons (ONU-UNITAR), Japón 2026",
    "category": "global",
    "year": 2026
  }
];
